# Generated by Django 5.2.7 on 2025-11-01 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pomodoro_duration', models.PositiveIntegerField(default=25, verbose_name='Длительность Pomodoro (мин)')),
                ('short_break_duration', models.PositiveIntegerField(default=5, verbose_name='Длительность короткого перерыва (мин)')),
                ('long_break_duration', models.PositiveIntegerField(default=15, verbose_name='Длительность длинного перерыва (мин)')),
                ('pomodoros_before_long_break', models.PositiveIntegerField(default=4, verbose_name='Pomodoro до длинного перерыва')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройки пользователя',
                'verbose_name_plural': 'Настройки пользователей',
            },
        ),
    ]
