# Generated by Django 5.2.7 on 2025-11-01 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductivityStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата статистики')),
                ('total_pomodoros_completed', models.PositiveIntegerField(default=0, verbose_name='Всего завершено Pomodoro')),
                ('total_tasks_completed', models.PositiveIntegerField(default=0, verbose_name='Всего завершено задач')),
                ('time_spent_per_quadrant', models.JSONField(default=dict, verbose_name='Время по квадрантам (JSON)')),
                ('quadrant_2_time', models.PositiveIntegerField(default=0, verbose_name='Время для Квадранта 2 (сек)')),
                ('planned_pomodoros', models.PositiveIntegerField(default=0, verbose_name='Запланировано Pomodoro')),
                ('completed_on_time_tasks', models.PositiveIntegerField(default=0, verbose_name='Задачи выполненные в срок')),
                ('focus_score', models.FloatField(default=0, verbose_name='Оценка фокуса (0-100)')),
                ('productivity_score', models.FloatField(default=0, verbose_name='Оценка продуктивности (0-100)')),
                ('interruptions_count', models.PositiveIntegerField(default=0, verbose_name='Количество прерываний')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Статистика продуктивности',
                'verbose_name_plural': 'Статистика продуктивности',
                'unique_together': {('user', 'date')},
            },
        ),
    ]
