# Generated by Django 5.2.7 on 2025-11-01 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EisenhowerQuadrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название квадранта')),
                ('description', models.TextField(verbose_name='Описание')),
                ('priority_order', models.IntegerField(verbose_name='Порядок отображения (1-4)')),
                ('color_code', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Цвет (HEX)')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Квадрант Эйзенхауэра',
                'verbose_name_plural': 'Квадранты Эйзенхауэра',
                'ordering': ['priority_order'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('active', 'Активная'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='active', max_length=10, verbose_name='Статус')),
                ('priority', models.PositiveIntegerField(default=1, verbose_name='Приоритет (1-10)')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Срок выполнения')),
                ('estimated_pomodoros', models.PositiveIntegerField(default=1, verbose_name='Планируемое количество Pomodoro')),
                ('completed_pomodoros', models.PositiveIntegerField(default=0, verbose_name='Выполнено Pomodoro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Фактическое время выполнения')),
                ('quadrant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.eisenhowerquadrant', verbose_name='Квадрант')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['quadrant__priority_order', 'priority', 'created_at'],
            },
        ),
    ]
