# Generated by Django 5.2.7 on 2025-11-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_add_quadrants_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['quadrant__priority_order', 'display_order', 'priority', 'created_at'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AddField(
            model_name='task',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок отображения'),
        ),
    ]
