# Generated by Django 5.2.7 on 2025-12-01 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_make_quadrant_nullable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['quadrant__priority_order', 'display_order', 'created_at'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
